USE [master]
GO

CREATE DATABASE [PassOfficeDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PassOfficeDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PassOfficeDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PassOfficeDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\PassOfficeDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PassOfficeDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PassOfficeDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PassOfficeDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PassOfficeDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PassOfficeDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PassOfficeDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [PassOfficeDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PassOfficeDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PassOfficeDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PassOfficeDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PassOfficeDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PassOfficeDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PassOfficeDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PassOfficeDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PassOfficeDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PassOfficeDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PassOfficeDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PassOfficeDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PassOfficeDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PassOfficeDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PassOfficeDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PassOfficeDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PassOfficeDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PassOfficeDB] SET RECOVERY FULL 
GO

ALTER DATABASE [PassOfficeDB] SET  MULTI_USER 
GO

ALTER DATABASE [PassOfficeDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PassOfficeDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PassOfficeDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PassOfficeDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PassOfficeDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PassOfficeDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PassOfficeDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PassOfficeDB] SET  READ_WRITE 
GO